-- MySQL Script generated by MySQL Workbench
-- Wed 05 Mar 2025 05:22:46 AM WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `CustomerID` INT NOT NULL,
  `customer_name` VARCHAR(45) NULL,
  `customer_phone` VARCHAR(30) NULL,
  `create_date` DATETIME NULL,
  `delete_date` DATE NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Items_Grocery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Items_Grocery` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Items_Grocery` (
  `Items_GroceryID` INT NOT NULL,
  `Items_Grocery_product` VARCHAR(45) NULL,
  `Items_Grocery_price` FLOAT NULL,
  `Items_Grocery_isbn` VARCHAR(45) NULL,
  `Items_Groceryc_quantity` INT NULL,
  `create_date` DATETIME NULL,
  `last_update` DATE NULL,
  PRIMARY KEY (`Items_GroceryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `EmployeeID` INT NOT NULL,
  `employee_name` VARCHAR(45) NULL,
  `employee_email` VARCHAR(70) NULL,
  `employee_role` VARCHAR(20) NULL,
  `create_date` DATETIME NULL,
  `DELETED_ADD` DATE NULL,
  PRIMARY KEY (`EmployeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transaction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transaction` (
  `TransactionID` INT NOT NULL AUTO_INCREMENT,
  `transaction_date` DATETIME NULL,
  `Items_GroceryID` INT NOT NULL,
  `total_amount` FLOAT NULL,
  `CustomerID` INT NULL,
  `EmployeeID` INT NULL,
  `create_date` DATE NULL,
  PRIMARY KEY (`TransactionID`),
  INDEX `index2` (`Items_GroceryID` ASC),
  INDEX `fk_transaction_customer_idx` (`CustomerID` ASC),
  INDEX `fk_transaction__employee_idx` (`EmployeeID` ASC),
  CONSTRAINT `fk_transaction_customer`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_items_grocery`
    FOREIGN KEY (`Items_GroceryID`)
    REFERENCES `mydb`.`Items_Grocery` (`Items_GroceryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction__employee`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `mydb`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Update_Stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Update_Stock` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Update_Stock` (
  `Update_StockID` INT NOT NULL,
  `Update_Stock_product` VARCHAR(45) NULL,
  `Update_Stock_quantity` INT NULL,
  `EmployeeID` INT NULL,
  `Items_GroceryID` INT NULL,
  `create_date` DATETIME NULL,
  `last_update` DATE NULL,
  PRIMARY KEY (`Update_StockID`),
  INDEX `fk_Update_Stock_Grocery_idx` (`Items_GroceryID` ASC),
  INDEX `fk_Update_Stock_employee_idx` (`EmployeeID` ASC),
  CONSTRAINT `fk_Update_Stock_Grocery`
    FOREIGN KEY (`Items_GroceryID`)
    REFERENCES `mydb`.`Items_Grocery` (`Items_GroceryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Update_Stock_employee`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `mydb`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE VIEW customer_transaction AS
	SELECT c.CustomeriD, c.customer_name, i.Items_Grocery_product, t.total_amount, t.transaction_date
	FROM transaction t
	JOIN customer c ON t.CustomerID = c.CustomerID
	JOIN Items_Grocery i ON t.Items_GroceryID = i.Items_GroceryID;

CREATE VIEW employee_transaction AS
  SELECT e.EmployeeID, e.employee_name, i.Items_Grocery_product, t.total_amount, t.transaction_date
  FROM transaction t
  JOIN Employee e ON t.EmployeeID = e.EmployeeID
  JOIN Items_Grocery i ON t.Items_GroceryID = i.Items_GroceryID;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
